\restrict D559wUbLqycPWfHsnV8VKPkeJtHP57PSjfdKy5Nzw4Y5InwEGdhLrPivat1yE5I
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE SCHEMA public;
ALTER SCHEMA public OWNER TO pg_database_owner;
COMMENT ON SCHEMA public IS 'standard public schema';
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE public.albums (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    class character varying(50) NOT NULL,
    nationality character varying(50) NOT NULL,
    description text,
    capacity integer DEFAULT 0 NOT NULL,
    cover_image character varying(500)
);
ALTER TABLE public.albums OWNER TO postgres;
ALTER TABLE public.albums ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.albums_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.exchanges (
    id integer NOT NULL,
    offer_id integer NOT NULL,
    accepter_user_id integer NOT NULL,
    offered_quantity integer NOT NULL,
    received_quantity integer NOT NULL,
    date_completed timestamp without time zone,
    status character varying(20) DEFAULT 'completed'::character varying NOT NULL,
    offered_wallet_id integer,
    received_wallet_id integer
);
ALTER TABLE public.exchanges OWNER TO postgres;
ALTER TABLE public.exchanges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchanges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.offer_rejections (
    id integer NOT NULL,
    offer_id integer NOT NULL,
    user_id integer NOT NULL,
    date_created timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);
ALTER TABLE public.offer_rejections OWNER TO postgres;
ALTER TABLE public.offer_rejections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offer_rejections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.offers (
    id integer NOT NULL,
    offerer_user_id integer NOT NULL,
    offered_quantity integer NOT NULL,
    offered character varying(20) NOT NULL,
    request character varying(20) NOT NULL,
    request_quantity integer NOT NULL,
    date_created timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    date_expires timestamp without time zone NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    offer_wallet_id integer
);
ALTER TABLE public.offers OWNER TO postgres;
ALTER TABLE public.offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.packs (
    id integer NOT NULL,
    album_id integer NOT NULL,
    class character varying(50) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer DEFAULT 0 NOT NULL,
    capacity integer DEFAULT 7 NOT NULL,
    cover_image character varying(500)
);
ALTER TABLE public.packs OWNER TO postgres;
ALTER TABLE public.packs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.packs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.packs_wallet (
    id integer NOT NULL,
    user_id integer NOT NULL,
    pack_id integer NOT NULL,
    stock integer DEFAULT 0 NOT NULL
);
ALTER TABLE public.packs_wallet OWNER TO postgres;
ALTER TABLE public.packs_wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.packs_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.prize (
    id integer NOT NULL,
    id_sticker integer,
    id_packs_bronce integer,
    id_packs_plateado integer,
    id_packs_dorado integer,
    spins integer NOT NULL,
    is_empty boolean DEFAULT false NOT NULL,
    probabily numeric(5,4) NOT NULL
);
ALTER TABLE public.prize OWNER TO postgres;
ALTER TABLE public.prize ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prize_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.purchases (
    id integer NOT NULL,
    user_id integer NOT NULL,
    store_id integer NOT NULL,
    quantity integer NOT NULL,
    total_usd numeric(10,2) NOT NULL,
    discount_usd numeric(10,2) DEFAULT 0.00 NOT NULL,
    purchased_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);
ALTER TABLE public.purchases OWNER TO postgres;
ALTER TABLE public.purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.spins_wallet (
    id integer NOT NULL,
    user_id integer NOT NULL,
    stock integer DEFAULT 0 NOT NULL
);
ALTER TABLE public.spins_wallet OWNER TO postgres;
ALTER TABLE public.spins_wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spins_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.stickers (
    id integer NOT NULL,
    album_id integer NOT NULL,
    class character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    nationality character varying(50) NOT NULL,
    cover_image character varying(500)
);
ALTER TABLE public.stickers OWNER TO postgres;
ALTER TABLE public.stickers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stickers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.stickers_wallet (
    id integer NOT NULL,
    user_id integer NOT NULL,
    sticker_id integer NOT NULL,
    stock integer DEFAULT 0 NOT NULL
);
ALTER TABLE public.stickers_wallet OWNER TO postgres;
ALTER TABLE public.stickers_wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stickers_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.store (
    id integer NOT NULL,
    pack_id integer,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    price_usd numeric(10,2) NOT NULL,
    discount_usd numeric(10,2) DEFAULT 0.00 NOT NULL,
    discount_active numeric(10,2) DEFAULT 0.00 NOT NULL,
    stock_available integer DEFAULT 0 NOT NULL,
    cover_image character varying(500) NOT NULL,
    product_type character varying(20) NOT NULL
);
ALTER TABLE public.store OWNER TO postgres;
CREATE TABLE public.store_combo_items (
    id integer NOT NULL,
    store_id integer NOT NULL,
    pack_id integer,
    spin_quantity integer DEFAULT 0,
    quantity integer DEFAULT 1 NOT NULL
);
ALTER TABLE public.store_combo_items OWNER TO postgres;
ALTER TABLE public.store_combo_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_combo_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE public.store ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.user_album_stickers (
    id integer NOT NULL,
    user_id integer NOT NULL,
    album_id integer NOT NULL,
    sticker_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.user_album_stickers OWNER TO postgres;
ALTER TABLE public.user_album_stickers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_album_stickers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    date_of_birth date NOT NULL,
    nationality character varying(50) NOT NULL,
    profile_picture character varying(500),
    email character varying(255) NOT NULL,
    phone_number character varying(20),
    password character varying(255) NOT NULL,
    role character varying(10) DEFAULT 'user'::character varying NOT NULL
);
ALTER TABLE public.users OWNER TO postgres;
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.winners (
    id integer NOT NULL,
    user_id integer NOT NULL,
    album_id integer NOT NULL,
    prize character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.winners OWNER TO postgres;
ALTER TABLE public.winners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.winners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
COPY public.albums (id, name, class, nationality, description, capacity, cover_image) FROM stdin;
1	Seleccion Argentina	mundial	argentina	La Selección Argentina de Fútbol es el equipo nacional que representa a la Argentina en competiciones internacionales. Es una de las selecciones más exitosas del mundo, con una rica historia y una gran pasión popular. Ha ganado tres Copas del Mundo (1978, 1986 y 2022) y múltiples títulos continentales, incluyendo la Copa América. Con figuras legendarias como Diego Maradona, Lionel Messi y muchos otros, la "Albiceleste" es símbolo de talento, garra y orgullo nacional.	15	/home/myh/Escritorio/web_workspace/figusApp-BackEnd/uploads/private/albums/1/portada.png
2	Seleccion Brasilera	mundial	brasil	La Selección de Brasil de Fútbol, conocida como la "Canarinha", es la más ganadora en la historia de los Mundiales, con cinco Copas del Mundo (1958, 1962, 1970, 1994 y 2002). Famosa por su estilo alegre y ofensivo, el "jogo bonito", Brasil ha dado al fútbol algunas de sus mayores leyendas, como Pelé, Zico, Ronaldo, Ronaldinho y Neymar. Es símbolo de talento, pasión y creatividad, y representa la esencia del fútbol sudamericano.	15	/home/myh/Escritorio/web_workspace/figusApp-BackEnd/uploads/private/albums/2/portada.png
3	Seleccion Francesa	mundial	francia	La Selección de Francia de Fútbol, conocida como "Les Bleus", es una de las potencias más importantes del fútbol mundial. Ha ganado dos Copas del Mundo (1998 y 2018) y varias Eurocopas, destacándose por su estilo de juego técnico y dinámico. Con generaciones de grandes figuras como Zidane, Henry, Mbappé y Griezmann, Francia combina juventud, talento y disciplina táctica, siendo un referente del fútbol moderno.	15	/home/myh/Escritorio/web_workspace/figusApp-BackEnd/uploads/private/albums/3/portada.png
\.
COPY public.exchanges (id, offer_id, accepter_user_id, offered_quantity, received_quantity, date_completed, status, offered_wallet_id, received_wallet_id) FROM stdin;
\.
COPY public.offer_rejections (id, offer_id, user_id, date_created) FROM stdin;
\.
COPY public.offers (id, offerer_user_id, offered_quantity, offered, request, request_quantity, date_created, date_expires, status, offer_wallet_id) FROM stdin;
\.
COPY public.packs (id, album_id, class, price, stock, capacity, cover_image) FROM stdin;
1	1	Comun	1500.00	3000	5	uploads/public/store/packs/sobreComun.png
2	2	Comun	1500.00	3000	5	uploads/public/store/packs/sobreComun.png
3	3	Comun	1500.00	3000	5	uploads/public/store/packs/sobreComun.png
4	1	Rara	2300.00	2000	3	uploads/public/store/packs/sobrePlateado.png
5	2	Rara	2300.00	2000	3	uploads/public/store/packs/sobrePlateado.png
6	3	Rara	2300.00	2000	3	uploads/public/store/packs/sobrePlateado.png
7	1	Legendaria	5000.00	600	1	uploads/public/store/packs/sobreDorado.png
8	2	Legendaria	5000.00	600	1	uploads/public/store/packs/sobreDorado.png
9	3	Legendaria	5000.00	600	1	uploads/public/store/packs/sobreDorado.png
\.
COPY public.packs_wallet (id, user_id, pack_id, stock) FROM stdin;
1	35	1	2
2	35	2	5
3	35	3	5
4	35	4	2
5	35	5	2
6	35	6	0
7	35	7	0
8	35	8	0
9	35	9	0
10	1	1	3
11	1	4	1
12	3	2	2
13	3	7	1
14	4	3	4
15	4	9	2
\.
COPY public.prize (id, id_sticker, id_packs_bronce, id_packs_plateado, id_packs_dorado, spins, is_empty, probabily) FROM stdin;
\.
COPY public.purchases (id, user_id, store_id, quantity, total_usd, discount_usd, purchased_at) FROM stdin;
\.
COPY public.spins_wallet (id, user_id, stock) FROM stdin;
1	1	50
2	3	20
3	4	15
4	35	10
\.
COPY public.stickers (id, album_id, class, name, nationality, cover_image) FROM stdin;
1	1	Comun	Nicolas Otamendi	Argentina	/uploads/private/albums/1/1.png
2	1	Rara	Julian Alvarez	Argentina	/uploads/private/albums/1/2.png
3	1	Rara	Lautaro Martinez	Argentina	/uploads/private/albums/1/3.png
4	1	Comun	Alexis Mac Allister	Argentina	/uploads/private/albums/1/4.png
5	1	Rara	Enzo Fernandez	Argentina	/uploads/private/albums/1/5.png
6	1	Comun	Lisandro Martinez	Argentina	/uploads/private/albums/1/6.png
7	1	Comun	Rodrigo De Paul	Argentina	/uploads/private/albums/1/7.png
8	1	Comun	Cristian Romero	Argentina	/uploads/private/albums/1/8.png
9	1	Legendaria	Lionel Messi	Argentina	/uploads/private/albums/1/9.png
10	1	Comun	Emiliano Martinez	Argentina	/uploads/private/albums/1/10.png
11	1	Comun	Nahuel Molina	Argentina	/uploads/private/albums/1/11.png
12	1	Comun	Hinchada Argentina	Argentina	/uploads/private/albums/1/12.png
13	1	Rara	Copa Argentina	Argentina	/uploads/private/albums/1/13.png
14	1	Comun	Pelota Argentina	Argentina	/uploads/private/albums/1/14.png
15	1	Legendaria	Diego Maradona	Argentina	/uploads/private/albums/1/15.png
16	2	Rara	Endrik	Brasil	/uploads/private/albums/2/1.png
17	2	Legendaria	Neymar Jr	Brasil	/uploads/private/albums/2/2.png
18	2	Comun	Alisson Becker	Brasil	/uploads/private/albums/2/3.png
19	2	Comun	Richarlison	Brasil	/uploads/private/albums/2/4.png
20	2	Comun	Bruno Guimaraes	Brasil	/uploads/private/albums/2/5.png
21	2	Comun	Danilo	Brasil	/uploads/private/albums/2/6.png
22	2	Comun	Eder Militao	Brasil	/uploads/private/albums/2/7.png
23	2	Comun	Lucas Paqueta	Brasil	/uploads/private/albums/2/8.png
24	2	Comun	Rapinha	Brasil	/uploads/private/albums/2/9.png
25	2	Rara	Vinicius Jr	Brasil	/uploads/private/albums/2/10.png
26	2	Rara	Rodrygo	Brasil	/uploads/private/albums/2/11.png
27	2	Rara	Copa Brasil	Brasil	/uploads/private/albums/2/12.png
28	2	Comun	Hinchada Brasilera	Brasil	/uploads/private/albums/2/13.png
29	2	Comun	Escudo Brasil	Brasil	/uploads/private/albums/2/14.png
30	2	Legendaria	Pele	Brasil	/uploads/private/albums/2/15.png
31	3	Comun	Axel Disasi	Francia	/uploads/private/albums/3/1.png
32	3	Comun	Camiseta Francia	Francia	/uploads/private/albums/3/2.png
33	3	Comun	Kingsley Coman	Francia	/uploads/private/albums/3/3.png
34	3	Rara	Copa Francia	Francia	/uploads/private/albums/3/4.png
35	3	Comun	Fofana	Francia	/uploads/private/albums/3/5.png
36	3	Comun	Hinchada Francesa	Francia	/uploads/private/albums/3/6.png
37	3	Comun	Konate	Francia	/uploads/private/albums/3/7.png
38	3	Comun	Guendouzi	Francia	/uploads/private/albums/3/8.png
39	3	Comun	Tchuameni	Francia	/uploads/private/albums/3/9.png
40	3	Rara	Varane	Francia	/uploads/private/albums/3/10.png
41	3	Rara	Camavinga	Francia	/uploads/private/albums/3/11.png
42	3	Legendaria	Kylian Mbappe	Francia	/uploads/private/albums/3/12.png
43	3	Comun	Steve Mandanda	Francia	/uploads/private/albums/3/13.png
44	3	Rara	Vitinha	Francia	/uploads/private/albums/3/14.png
45	3	Legendaria	Zinedine Zidane	Francia	/uploads/private/albums/3/15.png
\.
COPY public.stickers_wallet (id, user_id, sticker_id, stock) FROM stdin;
18	35	28	1
19	35	4	4
20	35	5	1
21	35	6	2
23	35	8	3
24	35	9	4
25	35	10	3
26	35	11	1
27	35	12	2
28	35	35	4
30	35	18	1
31	35	1	1
32	35	2	1
33	35	7	1
34	35	3	1
35	35	13	1
36	1	1	2
37	1	9	1
38	3	17	3
39	3	30	1
40	4	42	2
41	4	45	1
\.
COPY public.store (id, pack_id, name, description, price_usd, discount_usd, discount_active, stock_available, cover_image, product_type) FROM stdin;
1	1	Sobre Bronce (Álbum 1)	Sobre individual de clase comun.	1500.00	0.00	0.00	5000	uploads/public/store/packs/sobreBronce.png	unidad
2	4	Sobre Plateado (Álbum 1)	Sobre individual de clase especial.	2300.00	0.00	0.00	3000	uploads/public/store/packs/sobrePlateado.png	unidad
3	7	Sobre Dorado (Álbum 1)	Sobre premium de clase legendaria.	5000.00	0.00	0.00	1000	uploads/public/store/packs/sobreDorado.png	unidad
4	\N	Combo Inicial	Incluye 3 sobres bronces del Álbum 1.	4200.00	300.00	1.00	2500	uploads/public/store/combos/comboInicial.png	combo
5	\N	Combo Pro	Incluye 2 sobres bronces y 1 sobre plateado del Álbum 1.	5200.00	400.00	1.00	1500	uploads/public/store/combos/comboPro.png	combo
6	\N	Combo Abanico	Incluye 1 bronce, 1 plateado y 1 dorado (Álbum 1).	7800.00	500.00	1.00	1000	uploads/public/store/combos/comboAbanico.png	combo
7	\N	Combo Elite	Incluye 2 sobres especiales y 1 sobre legendario.	9800.00	700.00	1.00	500	uploads/public/store/combos/comboElite.png	combo
8	\N	Giro Individual	Un giro individual para la ruleta de premios.	500.00	0.00	0.00	9999	uploads/public/store/spins/giroIndividual.png	spin
9	\N	Combo Ruleta Pro	Paquete de 10 giros para la ruleta.	4500.00	500.00	1.00	5000	uploads/public/store/spins/comboRuleta_v2.png	combo
10	\N	Combo Mix Mundial	¡De todo! 1 Sobre Bronce Álbum 1, 1 Sobre Bronce Álbum 2, 1 Sobre Bronce Álbum 3 y 5 Giros.	4800.00	700.00	1.00	800	uploads/public/store/combos/comboMix.png	combo
\.
COPY public.store_combo_items (id, store_id, pack_id, spin_quantity, quantity) FROM stdin;
1	4	1	0	3
2	5	1	0	2
3	5	4	0	1
4	6	1	0	1
5	6	4	0	1
6	6	7	0	1
7	7	4	0	2
8	7	7	0	1
9	9	\N	10	1
10	10	1	0	1
11	10	2	0	1
12	10	3	0	1
13	10	\N	5	1
\.
COPY public.user_album_stickers (id, user_id, album_id, sticker_id, created_at) FROM stdin;
1	35	1	1	2026-06-03 15:25:00
2	35	1	2	2026-06-03 15:25:00
3	35	1	3	2026-06-03 15:25:00
4	35	1	6	2026-06-03 20:21:32
5	35	1	5	2026-06-03 20:21:32
6	35	1	7	2026-06-03 20:21:32
7	35	1	8	2026-06-03 20:40:44
8	35	1	13	2026-06-03 20:40:44
9	35	1	10	2026-06-03 20:40:44
10	35	1	4	2026-06-03 20:40:44
11	35	1	9	2026-06-03 20:40:44
12	35	2	24	2026-06-03 20:42:04
13	35	3	32	2026-06-03 20:42:04
14	35	3	31	2026-06-03 20:42:04
15	35	2	21	2026-06-03 20:42:04
16	35	3	42	2026-06-03 20:59:04
17	35	2	27	2026-06-03 20:59:26
18	35	3	41	2026-06-03 20:59:39
298	35	1	11	2026-06-06 02:21:29
299	35	1	12	2026-06-06 02:21:29
300	35	1	14	2026-06-06 02:21:29
301	35	1	15	2026-06-06 02:21:29
302	35	2	16	2026-06-06 02:21:29
303	35	2	17	2026-06-06 02:21:29
304	35	2	18	2026-06-06 02:21:29
305	35	2	19	2026-06-06 02:21:29
306	35	2	20	2026-06-06 02:21:29
307	35	2	22	2026-06-06 02:21:29
308	35	2	23	2026-06-06 02:21:29
309	35	2	25	2026-06-06 02:21:29
310	35	2	26	2026-06-06 02:21:29
311	35	2	28	2026-06-06 02:21:29
312	35	2	29	2026-06-06 02:21:29
313	35	2	30	2026-06-06 02:21:29
314	35	3	33	2026-06-06 02:21:29
315	35	3	34	2026-06-06 02:21:29
316	35	3	35	2026-06-06 02:21:29
317	35	3	36	2026-06-06 02:21:29
318	35	3	37	2026-06-06 02:21:29
319	35	3	38	2026-06-06 02:21:29
320	35	3	39	2026-06-06 02:21:29
321	35	3	40	2026-06-06 02:21:29
322	35	3	43	2026-06-06 02:21:29
323	35	3	44	2026-06-06 02:21:29
324	35	3	45	2026-06-06 02:21:29
325	1	1	1	2026-06-12 10:00:00
326	1	1	9	2026-06-12 10:00:00
327	3	2	17	2026-06-12 11:30:00
328	3	2	30	2026-06-12 11:30:00
329	4	3	42	2026-06-12 12:45:00
330	4	3	45	2026-06-12 12:45:00
\.
COPY public.users (id, first_name, last_name, date_of_birth, nationality, profile_picture, email, phone_number, password, role) FROM stdin;
1	Martín	Lorenzi	2001-12-06	AR	uploads/private/users/1/profile.jpeg	alexmartin9c@gmail.com	5492983659821	$2b$10$j0.3lqSvlL9eBZpoGHpJ5.K0YCzvBZgGeNTWU5MpZLjYrLYiXuivq	admin
3	Carla	González	1995-11-22	Argentino	/home/myh/Escritorio/web_workspace/figusApp-BackEnd/uploads/private/users/3/pelota99.png	carla.gonzalez95@gmail.com	+54 9 11 2345-6789	$argon2id$v=19$m=65536,t=3,p=4$c2FsdHZhbHVlNzg5$testHashPlaceholderForCarlaGonzalez	user
4	Santiago	Rojas	2000-05-08	Argentino	/home/myh/Escritorio/web_workspace/figusApp-BackEnd/uploads/private/users/4/gato123.png	santi.rojas2000@hotmail.com	+54 9 351 678-9012	$argon2id$v=19$m=65536,t=3,p=4$c2FsdHZhbHVlMDEy$testHashPlaceholderForSantiagoRojas	user
35	Manuel	Irigoyen	1999-03-03	AR	uploads/private/users/35/profile.png	manu1234@hotmail.com	2983380740	$2b$10$3..n0kahh8MVn9vaIe6jVupZPcIbeIHC0uot0qwpEgKSvXUBrW1uy	user
\.
COPY public.winners (id, user_id, album_id, prize, created_at) FROM stdin;
\.
SELECT pg_catalog.setval('public.albums_id_seq', 1, false);
SELECT pg_catalog.setval('public.exchanges_id_seq', 1, false);
SELECT pg_catalog.setval('public.offer_rejections_id_seq', 1, false);
SELECT pg_catalog.setval('public.offers_id_seq', 1, false);
SELECT pg_catalog.setval('public.packs_id_seq', 1, false);
SELECT pg_catalog.setval('public.packs_wallet_id_seq', 1, false);
SELECT pg_catalog.setval('public.prize_id_seq', 1, false);
SELECT pg_catalog.setval('public.purchases_id_seq', 1, false);
SELECT pg_catalog.setval('public.spins_wallet_id_seq', 1, false);
SELECT pg_catalog.setval('public.stickers_id_seq', 1, false);
SELECT pg_catalog.setval('public.stickers_wallet_id_seq', 1, false);
SELECT pg_catalog.setval('public.store_combo_items_id_seq', 1, false);
SELECT pg_catalog.setval('public.store_id_seq', 1, false);
SELECT pg_catalog.setval('public.user_album_stickers_id_seq', 1, false);
SELECT pg_catalog.setval('public.users_id_seq', 1, false);
SELECT pg_catalog.setval('public.winners_id_seq', 1, false);
ALTER TABLE ONLY public.albums
    ADD CONSTRAINT albums_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.exchanges
    ADD CONSTRAINT exchanges_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.offer_rejections
    ADD CONSTRAINT offer_rejections_offer_id_user_id_key UNIQUE (offer_id, user_id);
ALTER TABLE ONLY public.offer_rejections
    ADD CONSTRAINT offer_rejections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.packs
    ADD CONSTRAINT packs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.packs_wallet
    ADD CONSTRAINT packs_wallet_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.packs_wallet
    ADD CONSTRAINT packs_wallet_user_id_pack_id_key UNIQUE (user_id, pack_id);
ALTER TABLE ONLY public.prize
    ADD CONSTRAINT prize_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.spins_wallet
    ADD CONSTRAINT spins_wallet_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.stickers
    ADD CONSTRAINT stickers_album_id_name_key UNIQUE (album_id, name);
ALTER TABLE ONLY public.stickers
    ADD CONSTRAINT stickers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.stickers_wallet
    ADD CONSTRAINT stickers_wallet_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.stickers_wallet
    ADD CONSTRAINT stickers_wallet_user_id_sticker_id_key UNIQUE (user_id, sticker_id);
ALTER TABLE ONLY public.store_combo_items
    ADD CONSTRAINT store_combo_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.store
    ADD CONSTRAINT store_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_album_stickers
    ADD CONSTRAINT user_album_stickers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_album_stickers
    ADD CONSTRAINT user_album_stickers_user_id_album_id_sticker_id_key UNIQUE (user_id, album_id, sticker_id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.winners
    ADD CONSTRAINT winners_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.winners
    ADD CONSTRAINT winners_user_id_album_id_key UNIQUE (user_id, album_id);
CREATE INDEX idx_packs_album_id ON public.packs USING btree (album_id);
CREATE INDEX idx_packs_wallet_user_id ON public.packs_wallet USING btree (user_id);
CREATE INDEX idx_stickers_album_id ON public.stickers USING btree (album_id);
CREATE INDEX idx_stickers_name ON public.stickers USING btree (name);
CREATE INDEX idx_stickers_wallet_user_id ON public.stickers_wallet USING btree (user_id);
CREATE INDEX idx_store_combo_store_id ON public.store_combo_items USING btree (store_id);
CREATE INDEX idx_user_album_stickers_album ON public.user_album_stickers USING btree (album_id);
ALTER TABLE ONLY public.exchanges
    ADD CONSTRAINT exchanges_accepter_user_id_fkey FOREIGN KEY (accepter_user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.exchanges
    ADD CONSTRAINT exchanges_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id);
ALTER TABLE ONLY public.exchanges
    ADD CONSTRAINT exchanges_offered_wallet_id_fkey FOREIGN KEY (offered_wallet_id) REFERENCES public.stickers_wallet(id);
ALTER TABLE ONLY public.exchanges
    ADD CONSTRAINT exchanges_received_wallet_id_fkey FOREIGN KEY (received_wallet_id) REFERENCES public.stickers_wallet(id);
ALTER TABLE ONLY public.offer_rejections
    ADD CONSTRAINT offer_rejections_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.offer_rejections
    ADD CONSTRAINT offer_rejections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_offer_wallet_id_fkey FOREIGN KEY (offer_wallet_id) REFERENCES public.stickers_wallet(id);
ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_offerer_user_id_fkey FOREIGN KEY (offerer_user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.packs
    ADD CONSTRAINT packs_album_id_fkey FOREIGN KEY (album_id) REFERENCES public.albums(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.packs_wallet
    ADD CONSTRAINT packs_wallet_pack_id_fkey FOREIGN KEY (pack_id) REFERENCES public.packs(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.packs_wallet
    ADD CONSTRAINT packs_wallet_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.prize
    ADD CONSTRAINT prize_id_packs_bronce_fkey FOREIGN KEY (id_packs_bronce) REFERENCES public.packs(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.prize
    ADD CONSTRAINT prize_id_packs_dorado_fkey FOREIGN KEY (id_packs_dorado) REFERENCES public.packs(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.prize
    ADD CONSTRAINT prize_id_packs_plateado_fkey FOREIGN KEY (id_packs_plateado) REFERENCES public.packs(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.prize
    ADD CONSTRAINT prize_id_sticker_fkey FOREIGN KEY (id_sticker) REFERENCES public.stickers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.spins_wallet
    ADD CONSTRAINT spins_wallet_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.stickers
    ADD CONSTRAINT stickers_album_id_fkey FOREIGN KEY (album_id) REFERENCES public.albums(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.stickers_wallet
    ADD CONSTRAINT stickers_wallet_sticker_id_fkey FOREIGN KEY (sticker_id) REFERENCES public.stickers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.stickers_wallet
    ADD CONSTRAINT stickers_wallet_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.store_combo_items
    ADD CONSTRAINT store_combo_items_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.store(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.store
    ADD CONSTRAINT store_pack_id_fkey FOREIGN KEY (pack_id) REFERENCES public.packs(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.user_album_stickers
    ADD CONSTRAINT user_album_stickers_album_id_fkey FOREIGN KEY (album_id) REFERENCES public.albums(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.user_album_stickers
    ADD CONSTRAINT user_album_stickers_sticker_id_fkey FOREIGN KEY (sticker_id) REFERENCES public.stickers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.user_album_stickers
    ADD CONSTRAINT user_album_stickers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.winners
    ADD CONSTRAINT winners_album_id_fkey FOREIGN KEY (album_id) REFERENCES public.albums(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.winners
    ADD CONSTRAINT winners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;
GRANT ALL ON TABLE public.albums TO anon;
GRANT ALL ON TABLE public.albums TO authenticated;
GRANT ALL ON TABLE public.albums TO service_role;
GRANT ALL ON SEQUENCE public.albums_id_seq TO anon;
GRANT ALL ON SEQUENCE public.albums_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.albums_id_seq TO service_role;
GRANT ALL ON TABLE public.exchanges TO anon;
GRANT ALL ON TABLE public.exchanges TO authenticated;
GRANT ALL ON TABLE public.exchanges TO service_role;
GRANT ALL ON SEQUENCE public.exchanges_id_seq TO anon;
GRANT ALL ON SEQUENCE public.exchanges_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.exchanges_id_seq TO service_role;
GRANT ALL ON TABLE public.offer_rejections TO anon;
GRANT ALL ON TABLE public.offer_rejections TO authenticated;
GRANT ALL ON TABLE public.offer_rejections TO service_role;
GRANT ALL ON SEQUENCE public.offer_rejections_id_seq TO anon;
GRANT ALL ON SEQUENCE public.offer_rejections_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.offer_rejections_id_seq TO service_role;
GRANT ALL ON TABLE public.offers TO anon;
GRANT ALL ON TABLE public.offers TO authenticated;
GRANT ALL ON TABLE public.offers TO service_role;
GRANT ALL ON SEQUENCE public.offers_id_seq TO anon;
GRANT ALL ON SEQUENCE public.offers_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.offers_id_seq TO service_role;
GRANT ALL ON TABLE public.packs TO anon;
GRANT ALL ON TABLE public.packs TO authenticated;
GRANT ALL ON TABLE public.packs TO service_role;
GRANT ALL ON SEQUENCE public.packs_id_seq TO anon;
GRANT ALL ON SEQUENCE public.packs_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.packs_id_seq TO service_role;
GRANT ALL ON TABLE public.packs_wallet TO anon;
GRANT ALL ON TABLE public.packs_wallet TO authenticated;
GRANT ALL ON TABLE public.packs_wallet TO service_role;
GRANT ALL ON SEQUENCE public.packs_wallet_id_seq TO anon;
GRANT ALL ON SEQUENCE public.packs_wallet_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.packs_wallet_id_seq TO service_role;
GRANT ALL ON TABLE public.prize TO anon;
GRANT ALL ON TABLE public.prize TO authenticated;
GRANT ALL ON TABLE public.prize TO service_role;
GRANT ALL ON SEQUENCE public.prize_id_seq TO anon;
GRANT ALL ON SEQUENCE public.prize_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.prize_id_seq TO service_role;
GRANT ALL ON TABLE public.purchases TO anon;
GRANT ALL ON TABLE public.purchases TO authenticated;
GRANT ALL ON TABLE public.purchases TO service_role;
GRANT ALL ON SEQUENCE public.purchases_id_seq TO anon;
GRANT ALL ON SEQUENCE public.purchases_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.purchases_id_seq TO service_role;
GRANT ALL ON TABLE public.spins_wallet TO anon;
GRANT ALL ON TABLE public.spins_wallet TO authenticated;
GRANT ALL ON TABLE public.spins_wallet TO service_role;
GRANT ALL ON SEQUENCE public.spins_wallet_id_seq TO anon;
GRANT ALL ON SEQUENCE public.spins_wallet_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.spins_wallet_id_seq TO service_role;
GRANT ALL ON TABLE public.stickers TO anon;
GRANT ALL ON TABLE public.stickers TO authenticated;
GRANT ALL ON TABLE public.stickers TO service_role;
GRANT ALL ON SEQUENCE public.stickers_id_seq TO anon;
GRANT ALL ON SEQUENCE public.stickers_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.stickers_id_seq TO service_role;
GRANT ALL ON TABLE public.stickers_wallet TO anon;
GRANT ALL ON TABLE public.stickers_wallet TO authenticated;
GRANT ALL ON TABLE public.stickers_wallet TO service_role;
GRANT ALL ON SEQUENCE public.stickers_wallet_id_seq TO anon;
GRANT ALL ON SEQUENCE public.stickers_wallet_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.stickers_wallet_id_seq TO service_role;
GRANT ALL ON TABLE public.store TO anon;
GRANT ALL ON TABLE public.store TO authenticated;
GRANT ALL ON TABLE public.store TO service_role;
GRANT ALL ON TABLE public.store_combo_items TO anon;
GRANT ALL ON TABLE public.store_combo_items TO authenticated;
GRANT ALL ON TABLE public.store_combo_items TO service_role;
GRANT ALL ON SEQUENCE public.store_combo_items_id_seq TO anon;
GRANT ALL ON SEQUENCE public.store_combo_items_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.store_combo_items_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.store_id_seq TO anon;
GRANT ALL ON SEQUENCE public.store_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.store_id_seq TO service_role;
GRANT ALL ON TABLE public.user_album_stickers TO anon;
GRANT ALL ON TABLE public.user_album_stickers TO authenticated;
GRANT ALL ON TABLE public.user_album_stickers TO service_role;
GRANT ALL ON SEQUENCE public.user_album_stickers_id_seq TO anon;
GRANT ALL ON SEQUENCE public.user_album_stickers_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.user_album_stickers_id_seq TO service_role;
GRANT ALL ON TABLE public.users TO anon;
GRANT ALL ON TABLE public.users TO authenticated;
GRANT ALL ON TABLE public.users TO service_role;
GRANT ALL ON SEQUENCE public.users_id_seq TO anon;
GRANT ALL ON SEQUENCE public.users_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.users_id_seq TO service_role;
GRANT ALL ON TABLE public.winners TO anon;
GRANT ALL ON TABLE public.winners TO authenticated;
GRANT ALL ON TABLE public.winners TO service_role;
GRANT ALL ON SEQUENCE public.winners_id_seq TO anon;
GRANT ALL ON SEQUENCE public.winners_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.winners_id_seq TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict D559wUbLqycPWfHsnV8VKPkeJtHP57PSjfdKy5Nzw4Y5InwEGdhLrPivat1yE5I

